# site settings
title: Shubashree Baskar
subtitle: by HTML5 UP
email: shub2296@gmail.com
description: I am a master's student in Electrical and Computer Engineering at Georgia Tech. This website gives you a brief overview of my journey at Georgia Tech and prior. 
I would like to Quote Michelle Obama here on something that I relate to her in a big way "To me, there  was magic in the learning. I got a buzzy sort of satisfaction from it". 
Scroll down to know more about my interests.
baseurl: "/Shubashree" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url: https://500px.com/shub2296
github_url: https://github.com/Shubashree
linkedin_url: https://www.linkedin.com/in/shubashree-baskar/

# build settings
markdown: kramdown

sass:
  style: compressed

remote_theme: Shubashree/forty-jekyll-theme
